### ISSUE TITLE
Expand on stepper hat wiring?

### ISSUE THREAD

**Issue by surfrock66** [danclarke/WorkingStargateMk2Raspi#1]
I've never used a stepper hat on a pi before, I assume we just mount directly to the M1-M4 positions?  I think it would be useful to have more closeups with pinout labels for the boards.

I assume it's wired like this: https://cdn.shopify.com/s/files/1/0176/3274/products/2348-02_1024x1024.jpg?v=1545412188 except without the need for the power-in connector, and with the long gpio riser mentioned in the guide.

**Comment by danclarke** [comment]
The wiring is basically as per the Adafruit docs, assuming you're using their hat. It can be slightly different depending on the kind of stepper you use, but they've outlined it all. You can't always tell if you've wired the motor to go in one direction or the other, for that case there's a config (config.py) where you can specify FORWARD / BACKWARD for each motor.

The dedicated 12v power is important. You can solder wires from the PCB to the hat directly so it can be powered from the input 12v somewhat neatly.

**Comment by surfrock66** [comment]
I may be missing this, but for the 2 motors (Symbols and Chevron), which is wired to M1-M2, and which is M3-M4, of does that not matter/can be changed in software?

**Comment by danclarke** [comment]
The port number doesn't really matter, it's also configurable in the config.py. You set the number with the motor_chevron and motor_gate numbers. You'll know if you need to switch the numbers around if the gate barely rotates but the top chevron moves and the stepper clicks a lot.

You can check the comments in the config.py to see all of the various options. Almost everything is configurable.
